[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
description = "rust port of babel and closure compiler."
documentation = "https://rustdoc.swc.rs/swc_ecma_transforms_testing/"
edition       = "2021"
license       = "Apache-2.0"
name          = "swc_ecma_transforms_testing"
repository    = "https://github.com/swc-project/swc.git"
version       = "4.0.0"

[lib]
bench = false
path = "Source/lib.rs"

[dependencies]
ansi_term = { workspace = true }
anyhow = { workspace = true }
base64 = { workspace = true }
hex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
sourcemap = { workspace = true }
tempfile = { workspace = true }

swc_common = { version = "3.0.0", path = "../swc_common", features = [
  "sourcemap",
] }
swc_ecma_ast = { version = "3.0.0", path = "../swc_ecma_ast" }
swc_ecma_codegen = { version = "3.0.0", path = "../swc_ecma_codegen" }
swc_ecma_parser = { version = "4.0.0", path = "../swc_ecma_parser" }
swc_ecma_testing = { version = "3.0.0", path = "../swc_ecma_testing" }
swc_ecma_transforms_base = { version = "4.0.0", path = "../swc_ecma_transforms_base" }
swc_ecma_utils = { version = "4.0.0", path = "../swc_ecma_utils" }
swc_ecma_visit = { version = "3.0.0", path = "../swc_ecma_visit" }
testing = { version = "3.0.0", path = "../testing" }
