[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
description = "preset-env for the swc"
documentation = "https://rustdoc.swc.rs/swc_ecma_preset_env/"
edition = "2021"
include = ["Cargo.toml", "src/**/*.rs", "src/**/*.json", "data/**/*.json"]
license = "Apache-2.0"
name = "swc_ecma_preset_env"
repository = { workspace = true }
version = "0.220.0"

[lib]
bench = false
path = "Source/lib.rs"

[features]
default = ["serde-impl"]
serde-impl = ["serde"]

[dependencies]
anyhow = { workspace = true }
dashmap = { workspace = true }
indexmap = { workspace = true }
once_cell = { workspace = true }
semver = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"], optional = true }
serde_json = { workspace = true }
st-map = { workspace = true }

preset_env_base = { version = "0.5.0", path = "../preset_env_base" }
rustc-hash = { workspace = true }
string_enum = { version = "0.4.4", path = "../string_enum" }
swc_atoms = { version = "0.7.0", path = "../swc_atoms" }
swc_common = { version = "0.39.0", path = "../swc_common" }
swc_ecma_ast = { version = "0.120.0", path = "../swc_ecma_ast" }
swc_ecma_transforms = { version = "0.242.0", path = "../swc_ecma_transforms", features = [
	"compat",
	"proposal",
] }
swc_ecma_utils = { version = "0.136.0", path = "../swc_ecma_utils" }
swc_ecma_visit = { version = "0.106.0", path = "../swc_ecma_visit" }

[dev-dependencies]
codspeed-criterion-compat = { workspace = true }
criterion = { workspace = true }
pretty_assertions = { workspace = true }

swc_ecma_codegen = { version = "0.157.0", path = "../swc_ecma_codegen" }
swc_ecma_parser = { version = "0.151.0", path = "../swc_ecma_parser" }
testing = { version = "0.41.0", path = "../testing" }

[[bench]]
harness = false
name = "polyfills"
