[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
description = "Compatibility layer between estree and swc"
documentation = "https://rustdoc.swc.rs/swc_estree_compat/"
edition       = "2021"
include       = ["Cargo.toml", "src/**/*.rs"]
license       = "Apache-2.0"
name          = "swc_estree_compat"
repository    = "https://github.com/swc-project/swc.git"
version       = "6.0.0"

[package.metadata.docs.rs]
all-features = true

[lib]
bench = false
path = "Source/lib.rs"

[features]

[dependencies]
ahash = { workspace = true, features = ["compile-time-rng"] }
anyhow = { workspace = true }
copyless = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

swc_atoms = { version = "3.0.0", path = "../swc_atoms" }
swc_common = { version = "5.0.0", path = "../swc_common", features = [
  "sourcemap",
  "tty-emitter",
] }
swc_ecma_ast = { version = "5.0.0", path = "../swc_ecma_ast" }
swc_ecma_parser = { version = "6.0.0", path = "../swc_ecma_parser" }
swc_ecma_utils = { version = "6.0.0", path = "../swc_ecma_utils" }
swc_ecma_visit = { version = "5.0.0", path = "../swc_ecma_visit" }
swc_estree_ast = { version = "5.0.0", path = "../swc_estree_ast" }
swc_node_comments = { version = "5.0.0", path = "../swc_node_comments/" }

[dev-dependencies]
codspeed-criterion-compat = { workspace = true }
criterion = { workspace = true }
pretty_assertions = { workspace = true }

swc                 = { version = "8.0.0", path = "../swc" }
swc_ecma_ast        = { version = "5.0.0", path = "../swc_ecma_ast" }
swc_ecma_parser     = { version = "6.0.0", path = "../swc_ecma_parser" }
swc_ecma_transforms = { version = "7.0.0", path = "../swc_ecma_transforms/" }
testing             = { version = "5.0.0", path = "../testing" }
walkdir             = { workspace = true }

[[bench]]
harness = false
name = "babelify"
