[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
description = "CSS modules"
documentation = "https://rustdoc.swc.rs/swc_css_modules/"
edition = "2021"
include = ["Cargo.toml", "src/**/*.rs"]
license = "Apache-2.0"
name = "swc_css_modules"
repository = "https://github.com/swc-project/swc.git"
version = "0.35.0"

[lib]
bench = false
path = "Source/lib.rs"

[dependencies]
rustc-hash = { workspace = true }
serde = { workspace = true, features = ["derive"] }

swc_atoms = { version = "0.7.0", path = "../swc_atoms" }
swc_common = { version = "0.39.0", path = "../swc_common" }
swc_css_ast = { version = "0.146.0", path = "../swc_css_ast" }
swc_css_codegen = { version = "0.157.0", path = "../swc_css_codegen" }
swc_css_parser = { version = "0.156.0", path = "../swc_css_parser" }
swc_css_visit = { version = "0.145.0", path = "../swc_css_visit" }

[dev-dependencies]
indexmap = { workspace = true, features = ["serde"] }
serde_json = { workspace = true }

swc_css_compat = { version = "0.33.0", path = "../swc_css_compat" }
testing = { version = "0.41.0", path = "../testing" }
