[package]
edition = "2021"
license.workspace = true
name = "swc-releaser"
publish = false
repository = { workspace = true }
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
cargo_metadata = { workspace = true }
changesets = { workspace = true }
clap = { version = "4.5.20", features = ["derive"] }
indexmap = { workspace = true }
petgraph = { workspace = true }

[lib]
path = "Source/main.rs"
