[dependencies]
quote = { workspace = true }

[lib]
bench = false
path = "Source/lib.rs"
proc-macro = true

[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
edition = "2024"
exclude = ["artifacts.json", "index.node"]
license-file = "LICENSE"
name = "node_macro_deps"
publish = false
version = "0.1.0"
