[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
description = "SDK for authoring swc plugin"
documentation = "https://rustdoc.swc.rs/swc_plugin/"
edition = "2018"
license-file = "LICENSE"
name = "swc_plugin"
repository = "https://github.com/swc-project/swc.git"
version = "1.0.0"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lib]
bench = false
path = "Source/lib.rs"

[dependencies]
once_cell = { workspace = true }
