[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
description = "Macros for swc_ecma_codegen."
documentation = "https://rustdoc.swc.rs/swc_ecma_codegen_macros/"
edition = "2021"
license-file = "LICENSE"
name = "swc_ecma_codegen_macros"
repository = "https://github.com/swc-project/swc.git"
version = "1.0.0"

[lib]
bench = false
path = "Source/lib.rs"
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }

swc_macros_common = { version = "1.0.0", path = "../swc_macros_common" }

[dependencies.syn]
features = ["fold"]
workspace = true

[dependencies.quote]
workspace = true
