[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
description = "Commons for compat transforms"
documentation = "https://rustdoc.swc.rs/swc_ecma_compat_common/"
edition = "2021"
include = ["Cargo.toml", "src/**/*.rs"]
license = "Apache-2.0"
name = "swc_ecma_compat_common"
repository = "https://github.com/swc-project/swc.git"
version = "0.14.0"

[dependencies]
swc_common = { version = "0.40.0", path = "../swc_common" }
swc_ecma_ast = { version = "0.121.0", path = "../swc_ecma_ast" }
swc_ecma_utils = { version = "0.137.0", path = "../swc_ecma_utils" }
swc_ecma_visit = { version = "0.107.0", path = "../swc_ecma_visit" }
swc_trace_macro = { version = "1.0.0", path = "../swc_trace_macro" }

[lib]
path = "Source/lib.rs"
