[dependencies]
swc_common      = { version = "8.1.1", path = "../swc_common" }
swc_ecma_ast    = { version = "8.1.2", path = "../swc_ecma_ast" }
swc_ecma_utils  = { version = "12.0.1", path = "../swc_ecma_utils" }
swc_ecma_visit  = { version = "8.0.0", path = "../swc_ecma_visit" }
swc_trace_macro = { version = "2.0.1", path = "../swc_trace_macro" }
