[package]
authors       = ["강동윤 <kdy1997.dev@gmail.com>"]
description   = "Ecmascript"
documentation = "https://rustdoc.swc.rs/swc_ecmascript/"
edition       = { workspace = true }
license       = { workspace = true }
name          = "swc_ecmascript"
repository    = { workspace = true }
version       = "15.0.0"

[dev-dependencies]

[features]
codegen = ["swc_ecma_codegen"]
compat = ["swc_ecma_transforms/compat"]
concurrent = ["swc_ecma_minifier/concurrent"]
default = ["typescript-parser"]
minifier = ["swc_ecma_minifier"]
module = ["swc_ecma_transforms/module"]
optimization = ["swc_ecma_transforms/optimization"]
parser = ["swc_ecma_parser"]
preset_env = ["swc_ecma_preset_env"]
proposal = ["swc_ecma_transforms/proposal"]
quote = ["swc_ecma_quote"]
react = ["swc_ecma_transforms/react"]
rkyv-impl = ["swc_ecma_ast/rkyv-impl"]
transforms = ["swc_ecma_transforms"]
typescript = ["typescript-parser", "swc_ecma_transforms/typescript"]
typescript-parser = ["swc_ecma_parser/typescript"]
utils = ["swc_ecma_utils"]
visit = ["swc_ecma_visit"]

[lib]
bench = false
path = "Source/lib.rs"

[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
description = "Ecmascript"
documentation = "https://rustdoc.swc.rs/swc_ecmascript/"
edition = { workspace = true }
license-file = { workspace = true }
name = "swc_ecmascript"
repository = { workspace = true }
version = "12.0.0"

[package.metadata]

[package.metadata.docs]

[dependencies]
swc_ecma_ast        = { version = "8.1.0", path = "../swc_ecma_ast" }
swc_ecma_codegen    = { version = "8.0.2", path = "../swc_ecma_codegen", optional = true }
swc_ecma_minifier   = { version = "12.4.0", path = "../swc_ecma_minifier", optional = true }
swc_ecma_parser     = { version = "10.0.2", path = "../swc_ecma_parser", optional = true, default-features = false }
swc_ecma_preset_env = { version = "14.0.0", path = "../swc_ecma_preset_env", optional = true }
swc_ecma_quote      = { version = "10.0.0", path = "../swc_ecma_quote", optional = true }
swc_ecma_transforms = { version = "14.0.0", path = "../swc_ecma_transforms", optional = true }
swc_ecma_utils      = { version = "11.0.0", path = "../swc_ecma_utils", optional = true }
swc_ecma_visit      = { version = "8.0.0", path = "../swc_ecma_visit", optional = true }

[dev-dependencies]
par-core = { workspace = true, features = ["chili"] }
