[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
description = "scoped-tls, but with good error message"
documentation = "https://rustdoc.swc.rs/better_scoped_tls/"
edition = "2021"
license-file = "LICENSE"
name = "better_scoped_tls"
repository = "https://github.com/swc-project/swc.git"
version = "1.0.0"

[lib]
bench = false
path = "Source/lib.rs"

[dependencies]
scoped-tls = { workspace = true }
