[dependencies]
auto_impl = { workspace = true }
parking_lot = { workspace = true }
rayon       = { workspace = true }
rustc-hash  = { workspace = true }
serde       = { workspace = true, features = ["derive"] }
thiserror   = { workspace = true }

swc_atoms     = { version = "5.0.0", path = "../swc_atoms" }
swc_cached    = { version = "2.0.0", path = "../swc_cached" }
swc_common    = { version = "8.1.0", path = "../swc_common" }
swc_css_ast   = { version = "8.0.0", path = "../swc_css_ast" }
swc_css_visit = { version = "8.0.0", path = "../swc_css_visit" }
thiserror = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
swc_css_parser = { version = "8.0.0", path = "../swc_css_parser" }
testing        = { version = "9.0.0", path = "../testing" }
