[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
description = "Extensions for @swc/core (nodejs)"
documentation = "https://rustdoc.swc.rs/swc_ecma_ext_transforms/"
edition       = "2021"
license       = "Apache-2.0"
name          = "swc_ecma_ext_transforms"
repository    = "https://github.com/swc-project/swc.git"
version       = "4.0.0"

[lib]
bench = false
path = "Source/lib.rs"

[dependencies]
phf = { workspace = true, features = ["macros"] }

swc_atoms      = { version = "2.0.0", path = "../swc_atoms" }
swc_common     = { version = "3.0.0", path = "../swc_common" }
swc_ecma_ast   = { version = "3.0.0", path = "../swc_ecma_ast" }
swc_ecma_utils = { version = "4.0.0", path = "../swc_ecma_utils" }
swc_ecma_visit = { version = "3.0.0", path = "../swc_ecma_visit" }
