[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
description = "rust port of babel and closure compiler."
documentation = "https://rustdoc.swc.rs/swc_ecma_transforms_typescript/"
edition = "2021"
include = ["Cargo.toml", "src/**/*.rs"]
license = "Apache-2.0"
name = "swc_ecma_transforms_typescript"
repository = "https://github.com/swc-project/swc.git"
version = "0.201.0"

[lib]
bench = false
path = "Source/lib.rs"

[dependencies]
serde = { workspace = true, features = ["derive"] }

ryu-js = { workspace = true }
swc_atoms = { version = "0.7.0", path = "../swc_atoms" }
swc_common = { version = "0.39.0", path = "../swc_common" }
swc_ecma_ast = { version = "0.120.0", path = "../swc_ecma_ast" }
swc_ecma_transforms_base = { version = "0.148.0", path = "../swc_ecma_transforms_base" }
swc_ecma_transforms_react = { version = "0.194.0", path = "../swc_ecma_transforms_react" }
swc_ecma_utils = { version = "0.136.0", path = "../swc_ecma_utils" }
swc_ecma_visit = { version = "0.106.0", path = "../swc_ecma_visit" }

[dev-dependencies]
codspeed-criterion-compat = { workspace = true }
criterion = { workspace = true }

swc_ecma_codegen = { version = "0.157.0", path = "../swc_ecma_codegen" }
swc_ecma_parser = { version = "0.151.0", path = "../swc_ecma_parser" }
swc_ecma_transforms_compat = { version = "0.174.0", path = "../swc_ecma_transforms_compat" }
swc_ecma_transforms_proposal = { version = "0.182.0", path = "../swc_ecma_transforms_proposal" }
swc_ecma_transforms_testing = { version = "0.151.0", path = "../swc_ecma_transforms_testing" }
testing = { version = "0.41.0", path = "../testing" }

[[bench]]
harness = false
name = "compat"
