[dependencies]
once_cell = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
swc_atoms = { version = "5.0.0", path = "../swc_atoms" }
swc_common = { version = "8.0.1", path = "../swc_common" }
swc_css_ast = { version = "8.0.0", path = "../swc_css_ast" }
swc_css_visit = { version = "8.0.0", path = "../swc_css_visit" }

[lib]
bench = false
path = "Source/lib.rs"

[dependencies]
once_cell  = { workspace = true }
rustc-hash = { workspace = true }
serde      = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

swc_atoms     = { version = "5.0.0", path = "../swc_atoms" }
swc_common    = { version = "8.1.1", path = "../swc_common" }
swc_css_ast   = { version = "8.0.0", path = "../swc_css_ast" }
swc_css_visit = { version = "8.0.0", path = "../swc_css_visit" }
